// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimplePhoneBook.Core.Repositories;

namespace SimplePhoneBook.Core.Migrations
{
    [DbContext(typeof(SimplePhoneBookDbContext))]
    partial class SimplePhoneBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SimplePhoneBook.Core.Entities.PhoneBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PhoneBooks");
                });

            modelBuilder.Entity("SimplePhoneBook.Core.Entities.PhoneBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("PhoneBookId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("PhoneBookId");

                    b.ToTable("PhoneBookEntries");
                });

            modelBuilder.Entity("SimplePhoneBook.Core.Entities.PhoneBookEntry", b =>
                {
                    b.HasOne("SimplePhoneBook.Core.Entities.PhoneBook", "PhoneBook")
                        .WithMany("PhoneBookEntries")
                        .HasForeignKey("PhoneBookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
